#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Mon Apr 27 15:01:00 BRT 2026
alwaysLogTamperWarnings=true
